### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bbc.co.uk', port=443): Max retries exceeded with url: /news/politics/constituencies/W07000049 (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))

### ISSUE THREAD

**Issue by Espade** [samirelanduk/election19#7]
When I run get_data.py, I got the error: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bbc.co.uk', port=443): Max retries exceeded with url: /news/politics/constituencies/W07000049 (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))

I think it is a request error? Have you seen something similar?

**Comment by samirelanduk** [comment]
Generally this happens if you have a bad connection, or change internet connections made connection attempt, or something like that. Does it happen everytime you run the script? Does it still happen now an hour or so later?

**Comment by Espade** [comment]
@samirelanduk Yeah, I found out this is an internet issue. But I still can not download all the data, could you please share the "data.json" ? Thank you So much!!!!

**Comment by samirelanduk** [comment]
Sure! I had to change the extension to .txt so github would let me upload it, but this is it:

[data.txt](https://github.com/samirelanduk/election19/files/4350103/data.txt)
